// src/elements/Card.vue
<script setup lang="ts">
  import { Icon } from "@iconify/vue";

  defineProps<{
    title?: string;
    icon?: string;
    titleTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    hasShadow?: boolean;
  }>();
</script>

<template>
  <div class="card-container" :class="{ 'has-shadow': hasShadow !== false }">
    <div v-if="title || icon || $slots.header_actions" class="card-header">
      <div class="card-header-main">
        <Icon v-if="icon" :icon="icon" width="24" height="24" />
        <component :is="titleTag || 'h3'" v-if="title" class="card-title">
          {{ title }}
        </component>
      </div>
      <div v-if="$slots.header_actions" class="card-header-actions">
        <slot name="header_actions"></slot>
      </div>
    </div>
    <div class="card-content">
      <slot></slot>
    </div>
  </div>
</template>

<style scoped>
  .card-container {
    background-color: var(--background-secondary);
    border-radius: var(--window-corner-radius);
    padding: 20px;
    display: flex;
    flex-direction: column;
    gap: 15px;
  }

  .card-container.has-shadow {
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  }

  .card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 12px;
    padding-bottom: 10px;
    border-bottom: 1px solid var(--background-primary);
  }

  .card-header-main {
    display: flex;
    align-items: center;
    gap: 12px;
  }

  .card-title {
    margin: 0;
    color: var(--primary-accent);
    font-size: 18px;
    font-weight: 500;
  }

  .card-header :deep(svg) {
    color: var(--primary-accent);
  }
</style>

// src/elements/Card.svelte
<script lang="ts">
  import Icon from "@iconify/svelte";

  /**
   * Props for the Card component.
   */
  interface Props {
    title?: string;
    icon?: string; // Iconify icon name string, e.g., "solar:home-linear"
    titleTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6"; // Optional: specify heading tag, defaults to h3
    hasShadow?: boolean; // Optional: whether the card has a box-shadow
  }

  let { title, icon, titleTag = "h3", hasShadow = true }: Props = $props();
</script>

<div class="card-container" class:has-shadow={hasShadow}>
  {#if title || icon || $$slots["header-actions"]}
    <div class="card-header">
      <div class="card-header-main">
        {#if icon}
          <Icon {icon} width="24" height="24" />
        {/if}
        {#if title}
          <svelte:element this={titleTag} class="card-title"
            >{title}</svelte:element
          >
        {/if}
      </div>
      {#if $$slots["header-actions"]}
        <div class="card-header-actions">
          <slot name="header-actions"></slot>
        </div>
      {/if}
    </div>
  {/if}
  <div class="card-content">
    <slot></slot>
  </div>
</div>

<style>
  .card-container {
    background-color: var(--background-secondary);
    border-radius: var(--window-corner-radius);
    padding: 20px;
    display: flex;
    flex-direction: column;
    gap: 15px; /* Gap between header (if present) and content */
  }

  .card-container.has-shadow {
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  }

  .card-header {
    display: flex;
    justify-content: space-between; /* Aligns title/icon to left, actions to right */
    align-items: center;
    gap: 12px;
    padding-bottom: 10px;
    border-bottom: 1px solid var(--background-primary);
  }

  .card-header-main {
    display: flex;
    align-items: center;
    gap: 12px; /* Gap between icon and title */
  }

  .card-title {
    /* Applied to the dynamic <svelte:element> */
    margin: 0;
    color: var(--primary-accent);
    font-size: 18px; /* Standardized card title size */
    font-weight: 500; /* Inter Medium, common for titles */
  }

  .card-header :global(svg) {
    /* For the icon in card-header-main */
    color: var(--primary-accent);
  }

  .card-header-actions {
    /* Allows for buttons or other controls on the right side of the header */
  }

  .card-content {
    /* Content fills the rest of the card. Padding is handled by card-container. */
  }
</style>
