// src/components/Sidebar.vue
<script setup lang="ts">
  import { currentView } from "@lib/viewStore";
  import { isSidebarExpanded, expandSidebar, collapseSidebar } from "@lib/sidebarStore";
  import LocalIcon from "@icons/Icon.vue";
  import { Icon as IconifyIcon } from "@iconify/vue";
</script>

<template>
  <nav :class="{ expanded: isSidebarExpanded }" @mouseenter="expandSidebar"
       @mouseleave="collapseSidebar">
    <img src="/logo.png" alt="CS2Tools Logo" class="logo" />
    <ul>
      <li>
        <a href="#/" :class="{ active: currentView === 'dashboard' }">
          <LocalIcon iconName="home" />
          <span v-if="isSidebarExpanded">Dashboard</span>
        </a>
      </li>
      <li>
        <a href="#/process-management"
           :class="{ active: currentView === 'process-management' }">
          <LocalIcon iconName="tasks" />
          <span v-if="isSidebarExpanded">Process Management</span>
        </a>
      </li>
      <li>
        <a href="#/power-plan-management"
           :class="{ active: currentView === 'power-plan-management' }">
          <LocalIcon iconName="power" />
          <span v-if="isSidebarExpanded">Power Plan Management</span>
        </a>
      </li>
      <li>
        <a href="#/cpu-affinity"
           :class="{ active: currentView === 'cpu-affinity' }">
          <IconifyIcon icon="solar:cpu-linear" width="24" height="24" />
          <span v-if="isSidebarExpanded">CPU Core Affinity</span>
        </a>
      </li>
      <li>
        <a href="#/nvidia-vibrance"
           :class="{ active: currentView === 'nvidia-vibrance' }">
          <IconifyIcon icon="solar:monitor-camera-linear" width="24"
                       height="24" />
          <span v-if="isSidebarExpanded">Nvidia Vibrance</span>
        </a>
      </li>
      <li>
        <a href="#/settings" :class="{ active: currentView === 'settings' }">
          <LocalIcon iconName="settings" />
          <span v-if="isSidebarExpanded">Settings</span>
        </a>
      </li>
    </ul>
  </nav>
</template>

<style scoped>
  nav {
    position: fixed;
    top: 0;
    left: 0;
    height: 100vh;
    width: 60px;
    /* Collapsed width */
    background-color: black;
    padding-top: 20px;
    padding-inline: 6px;
    border-right: 1px solid var(--background-primary);
    transition: width 0.15s ease-in-out;
    overflow-x: hidden;
    /* Hide text when collapsed */
    z-index: 100;
    /* Ensure sidebar stays on top */
    display: flex;
    flex-direction: column;
    justify-content: center;
    gap: 40px;
  }

  nav.expanded {
    width: 270px;
    /* Expanded width */
  }

  ul {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  li {
    width: 100%;
    /* Center logo */
    display: flex;
    justify-content: center;
    /* Horizontally center content in collapsed state */
  }

  /* Logo styling */
  .logo {
    display: block;
    width: 46px;
    height: auto;
    justify-self: flex-start;

    nav.expanded & {
      width: 80px;
      margin-bottom:
    }
  }

  nav.expanded li {
    justify-content: flex-start;
    /* Align left when expanded */
    /* padding-left: 20px; */
  }

  a {
    display: flex;
    align-items: center;
    text-decoration: none;
    color: var(--text-secondary);
    width: 100%;
    /* Fill li width */
    padding: 12px;
    border-radius: 8px;
    /* Soft corners for hover effect */
    transition: background-color 0.2s, color 0.2s;
    gap: 15px;
    /* Space between icon and text */
    white-space: nowrap;
    /* Prevent text wrapping */
  }

  /* Centered icons when collapsed */
  nav:not(.expanded) a {
    justify-content: center;
    padding: 12px 0;
    /* Remove side padding to center properly */
  }

  nav.expanded a {
    padding: 12px 15px;
    /* Restore padding */
    justify-content: flex-start;
  }

  a:hover {
    background-color: var(--background-secondary, #242424);
    color: var(--text-primary);
  }

  a.active {
    background-color: var(--background-secondary, #242424);
    color: var(--primary-accent);
    font-weight: 500;
  }

  /* Icon coloring for active state */
  /* Target both SVG types */
  a.active :deep(svg) {
    /* color: var(--primary-accent) !important; */
    fill: var(--primary-accent);
    /* For filled icons */
    /* color: var(--primary-accent); */
  }

  /* Make sure stroke-based icons also get colored if you use them */
  /*
  a.active :deep(path) {
      stroke: var(--primary-accent);
  }
  */

  span {
    font-size: 16px;
    /* fade in text */
    animation: fadeIn 0.2s ease-in;
  }

  @keyframes fadeIn {
    from {
      opacity: 0;
    }

    to {
      opacity: 1;
    }
  }
</style>

// src/components/Sidebar.svelte
<script lang="ts">
  // import Icon from "@iconify/svelte";
  import { currentView } from "@lib/viewStore.svelte.ts";
  import {
    isSidebarExpanded,
    expandSidebar,
    collapseSidebar,
  } from "@lib/sidebarStore.svelte.ts";
  import Icon from "@icons/Icon.svelte";
  import Iconify from "@iconify/svelte";

  // Local state for isExpanded is removed, now using store
</script>

<nav
  class:expanded={$isSidebarExpanded}
  on:mouseenter={expandSidebar}
  on:mouseleave={collapseSidebar}
>
  <ul>
    <!-- {#if $isSidebarExpanded}
      <li class="sidebar-title">CS2Tools by Jonny</li>
    {/if} -->
    <li>
      <img src="/logo.png" alt="CS2Tools Logo" class="logo" />
    </li>
    <li>
      <a href="#/" class:active={$currentView === "dashboard"}>
        <!-- <Icon icon="solar:home-smile-linear" width="24" height="24" /> -->
        <Icon iconName="home" />
        {#if $isSidebarExpanded}<span>Dashboard</span>{/if}
      </a>
    </li>
    <li>
      <a
        href="#/process-management"
        class:active={$currentView === "process-management"}
      >
        <Icon iconName="tasks" />
        {#if $isSidebarExpanded}<span>Process Management</span>{/if}
      </a>
    </li>
    <li>
      <a
        href="#/power-plan-management"
        class:active={$currentView === "power-plan-management"}
      >
        <Icon iconName="power" />
        {#if $isSidebarExpanded}<span>Power Plan Management</span>{/if}
      </a>
    </li>
    <li>
      <a
        href="#/nvidia-vibrance"
        class:active={$currentView === "nvidia-vibrance"}
      >
        <Iconify icon="solar:monitor-camera-linear" width="24" height="24" />
        {#if $isSidebarExpanded}<span>Nvidia Vibrance</span>{/if}
      </a>
    </li>
    <li>
      <a href="#/settings" class:active={$currentView === "settings"}>
        <Icon iconName="settings" />
        {#if $isSidebarExpanded}<span>Settings</span>{/if}
      </a>
    </li>
  </ul>
</nav>

<style scoped>
  nav {
    position: fixed;
    top: 0;
    left: 0;
    height: 100vh;
    width: 60px; /* Collapsed width */
    background-color: black;
    padding-top: 20px;
    border-right: 1px solid var(--background-primary);
    transition: width 0.15s ease-in-out;
    overflow-x: hidden; /* Hide text when collapsed */
    z-index: 100; /* Ensure sidebar stays on top */

    &.expanded {
      width: 270px; /* Expanded width */
    }

    ul {
      list-style: none;
      padding: 0;
      margin: 0;
      margin-top: 40px;
      /* 
      nav.expanded & {
        margin-top: 0px;
      } */
    }

    /* .sidebar-title {
      display: flex;
      align-items: center;
      font-size: 20px;
      font-weight: 600;
      padding-inline: 20px;
      height: 80px;
      color: var(--primary-accent);
      white-space: nowrap;
    } */

    a {
      text-decoration: none;
      color: var(--text-primary);
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 15px 20px; /* Base padding, adjusted for icon centering when collapsed */
      font-size: 13px;
      font-weight: 400;
      transition:
        background-color 0.15s ease-in-out,
        color 0.15s ease-in-out;
      white-space: nowrap; /* Prevent text from wrapping */
      justify-content: center; /* Center icons when collapsed */

      span {
        opacity: 0;
        transition: opacity 0.15s ease-in-out;
        margin-left: 0; /* Ensure no extra margin when hidden */
      }

      &:hover {
        background-color: var(--background-primary);
        color: var(--primary-accent);
      }

      &.active {
        background-color: var(--primary-accent);
        color: var(--background-primary);
        font-weight: 600;

        /* Add this to change icon color when active */
        :global(svg) {
          color: var(
            --background-primary
          ); /* Or directly use #1A1A1A or black */
        }
      }

      :global(svg) {
        min-width: 24px; /* Ensure icons have a minimum width */
        color: currentColor;
        transition: color 0.15s ease-in-out;
      }
    }
  }

  nav.expanded li a {
    justify-content: flex-start; /* Align items to start when expanded */
    padding: 15px 20px; /* Restore original padding */
  }

  nav.expanded li a span {
    opacity: 1;
    margin-left: 0; /* Reset margin if any specific was added for collapsed */
  }

  .logo {
    width: 60px;
    height: auto;
    display: block;
    padding-inline: 8px;
    /* position: absolute;
    bottom: 20px; */
    transition: 0.15s ease-in-out;
    margin-bottom: 40px;

    nav.expanded & {
      translate: 100px 0; /* Move logo to the right when expanded */
      scale: 2.4;
    }
  }
</style>
